enum Time {
  DURATION = 40,
}

export const defaultTime = Time.DURATION;

export const possibleNouns = [
  "mexico",
  "bangalore",
  "flamingo",
  "evolution",
  "ostrich",
  "daydream",
  "Ladybug",
  "bookworm",
  "dragonfly",
  "overdue",
  "snowboard",
  "grasshopper",
  "thunderstorm",
  "backbreaker",
  "candlestick",
  "rearward",
  "rearrange",
  "steamship",
  "readywitted",
  "rattletrap",
  "nexus",
  "quintessence",
  "epiphany",
  "sempiternity",
  "limerence",
  "petrichor",
  "querencia",
  "mellifluence",
  "vicissitude",
  "pastiche",
];
export const moreAdjectives = [
  "resplendent",
  "irresolute",
  "enigmatic",
  "obfuscating",
  "ephemeral",
  "quixotic",
  "pernicious",
  "incandescent",
  "soporific",
  "labyrinthine",
  "phantasmagoric",
  "pulchritudinous",
  "verisimilitudinous",
  "effervescent",
  "serpentine",
  "diaphanous",
  "effulgent",
  "quixotic",
  "transient",
  "mellifluous",
];

export const moreTemplates = [
  "Nobody, {{nouns}} should begin to create {{nouns}} the wasted few societies, especially for {{nouns}} provided with their {{nouns}}",
  "Everyday, {{nouns}} lively begin to navigate {{nouns}} throughout, waves for {{nouns}} likelihood short {{nouns}} span",
  "Hello!, you are typing {{nouns}}, hoping to beat {{nouns}} highscore, don't think {{nouns}} signals singing wouldn't {{nouns}}",
  "Suddenly, {{nouns}} start to influence {{nouns}} across, quickly for {{nouns}} making intense {{nouns}} times",
  "Unexpectedly, {{nouns}} decide to interrupt {{nouns}} nearby, largely for {{nouns}} ignoring subtle {{nouns}} hints",
  "Frequently, {{nouns}} tend to observe {{nouns}} within, fully for {{nouns}} understanding brief {{nouns}} interactions",
  "Rarely, {{nouns}} manage to capture {{nouns}} through, scarcely for {{nouns}} maintaining limited {{nouns}} control",
  "Sometimes, {{nouns}} attempt to redesign {{nouns}} along, carefully for {{nouns}} preserving initial {{nouns}} concepts",
  "Often, {{nouns}} strive to enhance {{nouns}} amidst, strongly for {{nouns}} boosting overall {{nouns}} performance",
  "Briefly, {{nouns}} try to emulate {{nouns}} around, swiftly for {{nouns}} adopting rapid {{nouns}} techniques",
  "Generally, {{nouns}} hope to establish {{nouns}} beneath, clearly for {{nouns}} emphasizing core {{nouns}} principles",
  "Regularly, {{nouns}} need to compile {{nouns}} between, precisely for {{nouns}} organizing key {{nouns}} elements",
  "Quickly, {{nouns}} aim to construct {{nouns}} beyond, hastily for {{nouns}} shaping new {{nouns}} structures",
  "Slowly, {{nouns}} work to integrate {{nouns}} under, gradually for {{nouns}} forming complete {{nouns}} systems",
  "Happily, {{nouns}} choose to present {{nouns}} beside, joyfully for {{nouns}} showcasing unique {{nouns}} features",
  "Sadly, {{nouns}} find to dissolve {{nouns}} across, reluctantly for {{nouns}} breaking old {{nouns}} patterns",
  "Bravely, {{nouns}} move to challenge {{nouns}} alongside, fearlessly for {{nouns}} confronting difficult {{nouns}} tasks",
  "Wisely, {{nouns}} opt to refine {{nouns}} behind, smartly for {{nouns}} enhancing subtle {{nouns}} details",
  "Kindly, {{nouns}} offer to assist {{nouns}} around, gently for {{nouns}} supporting weak {{nouns}} structures",
  "{{nouns}}, {{nouns}} decide to protect {{nouns}} within, securely for {{nouns}} guarding valuable {{nouns}} resources",
];
